name: "release"

on:
  push:
    tags: ["*"]

permissions:
  contents: "write"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: "pkl-community/setup-pkl@v0"
        with:
          pkl-version: "0.26.3"

      - name: "Package"
        run: "./scripts/package.sh"
        env:
          PACKAGE_VERSION: "${{ github.ref_name }}"

      - name: "Release openapi@${{ github.ref_name }}"
        uses: "softprops/action-gh-release@v2"
        with:
          tag_name: "openapi@${{ github.ref_name }}"
          name: "openapi@${{ github.ref_name }}"
          body: |
            Release of openapi@${{ github.ref_name }}.
          files: |
            ./build/openapi@${{ github.ref_name }}*
          make_latest: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
